# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_type', models.CharField(choices=[('', '--'), ('car', 'car gears'), ('home', 'home gears'), ('electroics', 'electronic gears'), ('computers', 'computer gears'), ('office', 'office equipment gears'), ('medical', 'medical equipment gears')], max_length=100)),
                ('gear_producer', models.CharField(max_length=100)),
                ('gear_name', models.CharField(max_length=100)),
                ('gear_model', models.CharField(max_length=100)),
                ('gear_date', models.CharField(max_length=100)),
                ('gear_quality', models.CharField(choices=[('', '--'), ('E', 'excellent'), ('G', 'good'), ('B', 'bad')], max_length=100)),
                ('gear_availablity', models.BooleanField(max_length=100)),
                ('gear_owner', models.CharField(max_length=100)),
                ('gear_price', models.CharField(max_length=100)),
            ],
        ),
    ]
